apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 13.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "50"
  name: kube-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: kubeaid
  source:
    path: k8s/kds-kubeaid-test/kube-prometheus
    repoURL: https://github.com/EHP4321/KDS-kubeaid-test-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
